### ISSUE TITLE
Via stitching between layer IN1 and layer IN2

### ISSUE THREAD

**Issue by Light411** [LibreSolar/bms-c1#23]
Hey Martin, 

4 layers clearly made a difference :) 
May I suggest you to add some more GND vias to better stitch your 2 internal ground layers ? 
You do have quite a lot of signals transitioning from top to bottom but the return path has to also find it's way between In1 and In2 to follow the signal. You do have some spare space under U3 IC to add some extra GND vias, and also under and around U4. 
This way you will make sure that at medium frequency, the return path will still be on the right GND plane at the closest to your signal, both on the top and bottom side. 

![Capture d’écran du 2022-03-15 12-00-05](https://user-images.githubusercontent.com/22010135/158363759-b4a9b595-f342-42b1-bcb5-882a7600c6ec.png)

**Comment by martinjaeger** [comment]
Fixed with new v0.3 board design (now called BMS C1).
