### ISSUE TITLE
Power PCB: R2 has wrong package

### ISSUE THREAD

**Issue by martinjaeger** [LibreSolar/bms-c1#25]
Should be TO-263 and not TO-252.

**Comment by EarthLord** [comment]
There are TO-252 based resistors as well. What load capacitance are you using to calculate the wattage of precharge resistor?

**Comment by martinjaeger** [comment]
I assumed 5 mF bus capacitance and 60V.

Just realizing that the datasheet does actually say DPAK style: https://www.bourns.com/docs/Product-Datasheets/PWR163.pdf

It's definitely considerably larger, so I'll double-check the footprint dimensions.

**Comment by martinjaeger** [comment]
Package is fixed in new revision.
