### ISSUE TITLE
Switching off with button does not work

### ISSUE THREAD

**Issue by martinjaeger** [LibreSolar/bms-c1#26]
The TS2 / WAKE pin of the bq76952 is only pulled up during shutdown mode, but not during operation. Thus, the MCU cannot detect if the button is long-pressed to put the battery pack into sleep mode.

Even though the TS2 pin is a multi-purpose pin, it cannot be configured as an output, but only as a general purpose ADC input.

We need something like an additional external pull-up to the 3V3 rail.

**Comment by EarthLord** [comment]
Not sure if I understand this situation completely, wouldn't the internal pull up on STM32 help?

**Comment by martinjaeger** [comment]
You are right, that's probably sufficient. Will double-check this next week.

**Comment by martinjaeger** [comment]
New circuit introduced in new design. Will close the issue after testing.

**Comment by martinjaeger** [comment]
Fixed in current board design.
