### ISSUE TITLE
ESP32 CAN bus 

### ISSUE THREAD

**Issue by B-hafedh** [LibreSolar/bms-c1#30]
The ESP32 offers a CAN 2.0B interface(up to 1Mbit/s), and you use the STM32G0B1 CAN(FD) interface (up to 15Mbit/s).
So, my question is: can i use the ESP32 CAN to command an E-scooter Motor Control Board for example, or a 1Mbit/s speed is not enough ?

**Comment by martinjaeger** [comment]
It depends on the E-scooter motor controller. Most probably classical CAN with around 500 kbit/s will be fine.
