### ISSUE TITLE
The status of the project

### ISSUE THREAD

**Issue by Linjieqiang** [LibreSolar/bms-c1#35]
Thanks for your great work, I would like to ask if I can do a proofing test now? Or do I need to wait for the next version to improve?

**Comment by martinjaeger** [comment]
What do you mean by "normal"?

**Comment by martinjaeger** [comment]
As said, I'm still doing tests, so I can't promise everything works already. See the latest issue I just posted regarding a wrong pinout.

**Comment by martinjaeger** [comment]
I opened #37 for tracking of the testing progress, so I will close this issue.
