### ISSUE TITLE
Minor - correction on schematics

### ISSUE THREAD

**Issue by robm0162** [LibreSolar/bms-c1#49]
Just a couple of minor observations in file bms-c1.pdf - schematic for FET section.  Page is numbered 7/5 as is the next page - page numbering needs reset.

More importantly, on page 7/5 - the section showing the FETs for reverse polarity and CHG signals, the note in the bottom left corner says the gate resistors is 470ohm and bases a calculation on this, while the schematic shows these are 47ohm, not 470ohm.

**Comment by martinjaeger** [comment]
Thanks @robm0162 for the report. I didn't even know that the schematic numbers can be assigned (or have to be assigned) manually.

Also the calculation is now fixed. The time constant was reduced to allow for shorter switch-off during short circuit conditions, so 47 Ohm is correct.
