### ISSUE TITLE
CAN bus testing

### ISSUE THREAD

**Issue by Ananyaaynana** [LibreSolar/bms-c1#57]
We want to perform CAN bus testing with firmware at commit: 50b5bc5bdae9ee7609a8f9edb43ee9fb062481d9 for a custom board similar to 0.4v bms_c1.

The test document gives a brief description of the CAN bus testing. What are the steps to be followed for testing the CAN bus?

**Comment by martinjaeger** [comment]
The device should automatically start sending reports once connected to a bus.

The protocol is described [here](https://thingset.io/spec/v0.6/transports/can.html). Also see [here](https://thingset.io/spec/v0.6/annex/b_tools.html#can-under-linux) for some recommended tools to use under Linux.

**Comment by Ananyaaynana** [comment]
Thank you for the reply.
